version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - redis
  celery_worker:
    build: .
    command: celery -A celery_worker worker --pool=solo --loglevel=info
    deploy:
      mode: replicated
      replicas: 3
    restart: unless-stopped
    depends_on:
      - redis
      - app
      - find_duplicates_ai
  find_duplicates_ai:
    image: oleg36913/video_embed_api_img:v3
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - lance_data:/data
  flower:
    build: .
    command: celery -A celery_worker flower --port=5555
    restart: unless-stopped
    ports:
      - "5556:5555"
    depends_on:
      - app
      - redis
      - celery_worker

volumes:
  lance_data:
  redis_data: